### ISSUE TITLE
Share files through path_provider

### ISSUE THREAD

**Issue by Stnieder** [zhouteng0217/ShareExtend#1]
Is it possible to share a file, that I've exported to the application documents directory provided by the path_provider. I am asking this, because android throws me an error, if I try to do that. The error looks like this:

```
I/SimplePermission(20971): Checking permission : android.permission.WRITE_EXTERNAL_STORAGE
E/MethodChannel#share_extend(20971): Failed to handle method call
E/MethodChannel#share_extend(20971): java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.vendetta.recipe/app_flutter/file.json
E/MethodChannel#share_extend(20971): 	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
E/MethodChannel#share_extend(20971): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#share_extend(20971): 	at com.zt.shareextend.ShareExtendPlugin.getUriForFile(ShareExtendPlugin.java:83)
E/MethodChannel#share_extend(20971): 	at com.zt.shareextend.ShareExtendPlugin.share(ShareExtendPlugin.java:62)
E/MethodChannel#share_extend(20971): 	at com.zt.shareextend.ShareExtendPlugin.onMethodCall(ShareExtendPlugin.java:42)
E/MethodChannel#share_extend(20971): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#share_extend(20971): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:172)

```

**Comment by zhouteng0217** [comment]
you can just change the code of android project file "src/main/res/xml/file_provider_path.xml" to

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <paths>
        <root-path
            name="root_path"
            path="/" />
    </paths>
</resources>
```

or you can upgrade the plugin to version 1.0.3 that has fixed the problem and simplified the usage of the plugin.
