### ISSUE TITLE
: java.lang.SecurityException: Permission Denial: reading 

### ISSUE THREAD

**Issue by kw2019ltd** [zhouteng0217/ShareExtend#38]
hi iam using
  share_extend: ^1.1.5

iam seeting below errror in logs while trying to share photo.

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 3,257ms.
E/DatabaseUtils( 7632): Writing exception to parcel
E/DatabaseUtils( 7632): java.lang.SecurityException: Permission Denial: reading com.zt.shareextend.ShareExtendProvider uri content://kw.ltd.shadi_fitness_app.shareextend.fileprovider/%252Fdata%252Fuser%252F0%252Fkw.ltd.shadi_fitness_app%252Fcache%252FlibCachedImageData%252F0f0a29b0-9298-11ea-cbef-ddaf422651a7.jpg from pid=8584, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils( 7632): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
E/DatabaseUtils( 7632): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
E/DatabaseUtils( 7632): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:593)
E/DatabaseUtils( 7632): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:507)
E/DatabaseUtils( 7632): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
E/DatabaseUtils( 7632): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E/DatabaseUtils( 7632): 	at android.os.Binder.execTransact(Binder.java:994)

**Comment by sgehrman** [comment]
I'm seeing this in the console.

D/SurfaceUtils( 5299): disconnecting from surface 0x7d99566010, reason disconnectFromSurface
E/ContentProviderNative( 5299): onTransact error from {P:5415;U:1000}
E/DatabaseUtils( 5299): Writing exception to parcel
E/DatabaseUtils( 5299): java.lang.SecurityException: Permission Denial: reading com.zt.shareextend.ShareExtendProvider uri content://re.distantfutu.pathfinder.shareextend.fileprovider/%252Fstorage%252Femulated%252F0%252FAzRecorderFree%252F20200211_004433.mp4 from pid=5415, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils( 5299): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:781)
E/DatabaseUtils( 5299): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:645)
E/DatabaseUtils( 5299): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
E/DatabaseUtils( 5299): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:114)
E/DatabaseUtils( 5299): 	at android.os.Binder.execTransactInternal(Binder.java:1032)
E/DatabaseUtils( 5299): 	at android.os.Binder.execTransact(Binder.java:1005)

**Comment by sgehrman** [comment]
E/DatabaseUtils(25165): java.lang.SecurityException: Permission Denial: reading com.zt.shareextend.ShareExtendProvider uri content://re.distantfutu.pathfinder.shareextend.fileprovider/%252Fdata%252Fuser%252F0%252Fre.distantfutu.pathfinder%252Fcache%252FshareTheme.png from pid=25311, uid=1000 requires the provider be exported, or grantUriPermission()
