### ISSUE TITLE
Warnings about CharSequence and String

### ISSUE THREAD

**Issue by datovarh** [zhouteng0217/ShareExtend#53]
Hi, amazing work!

I have these warnings on Android, when I use shareMultiple with images, everything is ok but, I just wanted to say this to have cleaner code.

Thanks

----------------------------------

W/Bundle  (25424): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
W/Bundle  (25424): Attempt to cast generated internal exception:
W/Bundle  (25424): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
W/Bundle  (25424): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1302)
W/Bundle  (25424): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1076)
W/Bundle  (25424): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:7570)
W/Bundle  (25424): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:10415)
W/Bundle  (25424): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:10378)
W/Bundle  (25424): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1735)
W/Bundle  (25424): 	at android.app.Activity.startActivityForResult(Activity.java:4594)
W/Bundle  (25424): 	at android.app.Activity.startActivityForResult(Activity.java:4552)
W/Bundle  (25424): 	at android.app.Activity.startActivity(Activity.java:4917)
W/Bundle  (25424): 	at android.app.Activity.startActivity(Activity.java:4885)
W/Bundle  (25424): 	at com.zt.shareextend.Share.startChooserActivity(Share.java:104)
W/Bundle  (25424): 	at com.zt.shareextend.Share.share(Share.java:96)
W/Bundle  (25424): 	at com.zt.shareextend.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:29)
W/Bundle  (25424): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
W/Bundle  (25424): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/Bundle  (25424): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/Bundle  (25424): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/Bundle  (25424): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/Bundle  (25424): 	at android.os.Looper.loop(Looper.java:160)
W/Bundle  (25424): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
W/Bundle  (25424): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  (25424): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/Bundle  (25424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by stephane-couget** [comment]
Hello, this day. Any idea on how to get rid of this inner exception?
Thank you very much for your diligence. See you soon.

`﻿ +6 ms] W/Bundle  (15231): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
[        ] W/Bundle  (15231): Attempt to cast generated internal exception:
[        ] W/Bundle  (15231): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
[        ] W/Bundle  (15231): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1294)
[        ] W/Bundle  (15231): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1000)
[        ] W/Bundle  (15231): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:6355)
[        ] W/Bundle  (15231): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:9095)
[        ] W/Bundle  (15231): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:9058)
[        ] W/Bundle  (15231): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2212)
[        ] W/Bundle  (15231): 	at android.app.Activity.startActivityForResult(Activity.java:4286)
[        ] W/Bundle  (15231): 	at android.app.Activity.startActivityForResult(Activity.java:4244)
[        ] W/Bundle  (15231): 	at android.app.Activity.startActivity(Activity.java:4583)
[        ] W/Bundle  (15231): 	at android.app.Activity.startActivity(Activity.java:4551)
[        ] W/Bundle  (15231): 	at com.zt.shareextend.Share.startChooserActivity(Share.java:104)
[        ] W/Bundle  (15231): 	at com.zt.shareextend.Share.share(Share.java:96)
[        ] W/Bundle  (15231): 	at com.zt.shareextend.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:29)
[        ] W/Bundle  (15231): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] W/Bundle  (15231): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] W/Bundle  (15231): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
[        ] W/Bundle  (15231): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] W/Bundle  (15231): 	at android.os.MessageQueue.next(MessageQueue.java:323)
[        ] W/Bundle  (15231): 	at android.os.Looper.loop(Looper.java:136)
[        ] W/Bundle  (15231): 	at android.app.ActivityThread.main(ActivityThread.java:6138)
[        ] W/Bundle  (15231): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] W/Bundle  (15231): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
[        ] W/Bundle  (15231): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)`

**Comment by zhouteng0217** [comment]
This will be fixed on version 2.0.0.
